FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ui ./ui
COPY app ./app

ENV PYTHONPATH=/app
EXPOSE 8501
CMD ["streamlit", "run", "ui/App.py", "--server.port", "8501", "--server.address", "0.0.0.0"]


